//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignaloBot.DAL.SQL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClientScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClientScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SignaloBot.DAL.SQL.Resources.ClientScripts", typeof(ClientScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE NONCLUSTERED INDEX [IX_CategoryID] ON [dbo].[pref_UserCategorySettings] ([CategoryID]).
        /// </summary>
        public static string foreignKeyIndex_UserCategorySettings_CategoryID {
            get {
                return ResourceManager.GetString("foreignKeyIndex_UserCategorySettings_CategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE NONCLUSTERED INDEX [IX_CategoryID] ON [dbo].[pref_UserTopicSettings] ([CategoryID]).
        /// </summary>
        public static string foreignKeyIndex_UserTopicSettings_CategoryID {
            get {
                return ResourceManager.GetString("foreignKeyIndex_UserTopicSettings_CategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE INDEX [IX_pref_UserCategorySettings_CategoryID] ON [dbo].[pref_UserCategorySettings]([CategoryID]).
        /// </summary>
        public static string index_UserCategorySettings_CategoryID {
            get {
                return ResourceManager.GetString("index_UserCategorySettings_CategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE UNIQUE NONCLUSTERED INDEX [IX_pref_UserDeliveryTypeSettings_Address]
        ///ON [dbo].[pref_UserDeliveryTypeSettings]([Address]) WHERE [Address] IS NOT NULL.
        /// </summary>
        public static string index_UserDeliveryTypeSettings_Address {
            get {
                return ResourceManager.GetString("index_UserDeliveryTypeSettings_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE INDEX [IX_pref_UserTopicSettings_CategoryID] ON [dbo].[pref_UserTopicSettings]([CategoryID]).
        /// </summary>
        public static string index_UserTopicSettings_CategoryID {
            get {
                return ResourceManager.GetString("index_UserTopicSettings_CategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[pref_Address_Exists]
        ///	@Address NVARCHAR(1000),
        ///	@DeliveryType INT
        ///AS
        ///
        ///SELECT 1 as AddressExists WHERE
        ///EXISTS 
        ///	(SELECT 1 FROM pref_UserDeliveryTypeSettings
        ///	WHERE Address = @Address
        ///	AND DeliveryType = @DeliveryType)
        ///.
        /// </summary>
        public static string proc_Address_Exists {
            get {
                return ResourceManager.GetString("proc_Address_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[pref_UserDeliveryTypeSettings_SelectAll]	
        ///	@FirstIndex INT,
        ///	@LastIndex INT
        ///AS
        ///
        ///SELECT sub.UserID, sub.DeliveryType, sub.Address, sub.TimeZoneID,
        ///	sub.LastUserVisitUtc, sub.LastSendDateUtc, sub.IsEnabled, sub.IsEnabledOnNewTopic, sub.SendCount,
        ///	sub.NDRCount, sub.IsBlockedOfNDR, sub.BlockOfNDRResetCodeSendDateUtc, sub.BlockOfNDRResetCode,
        ///	up + down - 1 AS TotalRows FROM
        ///(	
        ///	SELECT s.*,
        ///		ROW_NUMBER() OVER(ORDER BY s.UserID) AS up,
        ///		ROW_NUMBER() OVER(ORDER BY s.UserID DE [rest of string was truncated]&quot;;.
        /// </summary>
        public static string proc_UserDeliveryTypeSettings_SelectAll {
            get {
                return ResourceManager.GetString("proc_UserDeliveryTypeSettings_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[pref_UserReceivePeriods_Rewrite]
        ///	@UserID UNIQUEIDENTIFIER,
        ///	@DeliveryType INT,
        ///	@CategoryID INT,
        ///	@Periods pref_UserReceivePeriodType READONLY
        ///AS
        ///
        ///DELETE pref_UserReceivePeriods
        ///WHERE UserID = @UserID
        ///AND DeliveryType = @DeliveryType
        ///AND CategoryID = @CategoryID
        ///
        ///INSERT pref_UserReceivePeriods (UserID, DeliveryType, CategoryID, PeriodOrder, PeriodBegin, PeriodEnd)
        ///SELECT @UserID, @DeliveryType, @CategoryID, PeriodOrder, PeriodBegin, PeriodEnd
        ///FROM @Periods.
        /// </summary>
        public static string proc_UserReceivePeriods_Rewrite {
            get {
                return ResourceManager.GetString("proc_UserReceivePeriods_Rewrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///CREATE PROCEDURE [dbo].[pref_UserTopicSettings_Select]
        ///	@UserID UNIQUEIDENTIFIER,
        ///	@FirstIndex INT,
        ///	@LastIndex INT,
        ///	@CategoryIDs pref_IntType READONLY
        ///AS
        ///
        ///SELECT sub.UserID, sub.CategoryID, sub.TopicID,
        ///	sub.AddDateUtc, sub.SendCount, sub.IsEnabled,
        ///	up + down - 1 AS TotalRows FROM
        ///(	
        ///	SELECT s.*,
        ///		ROW_NUMBER() OVER(ORDER BY s.AddDateUtc) AS up,
        ///		ROW_NUMBER() OVER(ORDER BY s.AddDateUtc DESC) AS down
        ///	FROM pref_UserTopicSettings s
        ///	JOIN @CategoryIDs c ON c.ID = s.CategoryID
        ///	WHERE s.Use [rest of string was truncated]&quot;;.
        /// </summary>
        public static string proc_UserTopicSettings_Select {
            get {
                return ResourceManager.GetString("proc_UserTopicSettings_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TYPE [dbo].[pref_CategoryType] AS TABLE(
        ///	[CategoryID] INT            NOT NULL,
        ///    [Name]       NVARCHAR (MAX) NOT NULL
        ///).
        /// </summary>
        public static string type_Category {
            get {
                return ResourceManager.GetString("type_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TYPE [dbo].[pref_GuidType] AS TABLE(
        ///	[ID] [uniqueidentifier] NOT NULL
        ///).
        /// </summary>
        public static string type_Guid {
            get {
                return ResourceManager.GetString("type_Guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TYPE [dbo].[pref_IntType] AS TABLE(
        ///	[ID] [int] NOT NULL
        ///).
        /// </summary>
        public static string type_Int {
            get {
                return ResourceManager.GetString("type_Int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TYPE [dbo].[pref_UpdateUserType] AS TABLE(
        ///	[UserID] [uniqueidentifier] NOT NULL,
        ///	[SendCount] [int] NOT NULL,
        ///	[DeliveryType] [int] NOT NULL,
        ///	[CategoryID] [int] NOT NULL,
        ///	[TopicID] [int] NULL
        ///).
        /// </summary>
        public static string type_UpdateUserType {
            get {
                return ResourceManager.GetString("type_UpdateUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TYPE [dbo].[pref_UserReceivePeriodType] AS TABLE(
        ///	[PeriodOrder] [int] NOT NULL,
        ///	[PeriodBegin] [Time] NOT NULL,
        ///	[PeriodEnd] [Time] NOT NULL
        ///).
        /// </summary>
        public static string type_UserReceivePeriod {
            get {
                return ResourceManager.GetString("type_UserReceivePeriod", resourceCulture);
            }
        }
    }
}
