//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignaloBot.DAL.SQL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SenderScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SenderScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SignaloBot.DAL.SQL.Resources.SenderScripts", typeof(SenderScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @ObjectName NVARCHAR(100)
        ///SELECT @ObjectName = OBJECT_NAME([default_object_id]) FROM SYS.COLUMNS
        ///WHERE [object_id] = OBJECT_ID(&apos;[dbo].[pref_Signals]&apos;) AND [name] = &apos;SignalDispatchID&apos;;
        ///
        ///EXEC(&apos;ALTER TABLE [dbo].[pref_Signals] DROP CONSTRAINT &apos; + @ObjectName)
        ///
        ///ALTER TABLE [dbo].[pref_Signals] ADD CONSTRAINT DF_SignalID_Default DEFAULT NEWSEQUENTIALID() FOR SignalDispatchID;.
        /// </summary>
        public static string alt_Signals_Default {
            get {
                return ResourceManager.GetString("alt_Signals_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TYPE [dbo].[pref_SignalSendDateType] AS TABLE(
        ///	[SignalDispatchID] [uniqueidentifier] NOT NULL,
        ///	[SendDateUtc] [datetime2](7) NOT NULL
        ///).
        /// </summary>
        public static string type_SignalSendDate {
            get {
                return ResourceManager.GetString("type_SignalSendDate", resourceCulture);
            }
        }
    }
}
