//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanatana.Notifications.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SenderInternalMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SenderInternalMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sanatana.Notifications.Resources.SenderInternalMessages", typeof(SenderInternalMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} parameter was not provided..
        /// </summary>
        public static string Common_ParameterMissing {
            get {
                return ResourceManager.GetString("Common_ParameterMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one {0} registered with {1} of \&quot;{2}\&quot;..
        /// </summary>
        public static string CompositionHandlerFactory_MoreThanOneFound {
            get {
                return ResourceManager.GetString("CompositionHandlerFactory_MoreThanOneFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} registered with {1} of \&quot;{2}\&quot;..
        /// </summary>
        public static string CompositionHandlerFactory_NotFound {
            get {
                return ResourceManager.GetString("CompositionHandlerFactory_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No template delivery type matched subscriber delivery type(s) {0}..
        /// </summary>
        public static string DispatchBuilder_NoTemplateMatched {
            get {
                return ResourceManager.GetString("DispatchBuilder_NoTemplateMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} registered with {1} of \&quot;{2}\&quot;..
        /// </summary>
        public static string DispatchChannelManager_NotFound {
            get {
                return ResourceManager.GetString("DispatchChannelManager_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal type {0} can not be sended with {1}. Expected type {2}..
        /// </summary>
        public static string Dispatcher_WrongInputType {
            get {
                return ResourceManager.GetString("Dispatcher_WrongInputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp storage file {0} is corrupted..
        /// </summary>
        public static string Filerepository_CorruptedFile {
            get {
                return ResourceManager.GetString("Filerepository_CorruptedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp storage file {0} is not a valid Guid..
        /// </summary>
        public static string Filerepository_InvalidGuidName {
            get {
                return ResourceManager.GetString("Filerepository_InvalidGuidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not invoke method on stopped instance of {0}. Need to Start {1} first..
        /// </summary>
        public static string InMemorySignalProvider_InvokeMethodInStoppedState {
            get {
                return ResourceManager.GetString("InMemorySignalProvider_InvokeMethodInStoppedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit can not be lower than 0..
        /// </summary>
        public static string LimitPeriod_LowerBound {
            get {
                return ResourceManager.GetString("LimitPeriod_LowerBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of parallel items processed can not be lower than 1..
        /// </summary>
        public static string ProcessorBase_ParallelNumberOutOfRange {
            get {
                return ResourceManager.GetString("ProcessorBase_ParallelNumberOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while delivering email to address {0}..
        /// </summary>
        public static string SmtpEmailSender_Fail {
            get {
                return ResourceManager.GetString("SmtpEmailSender_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smtp exception while delivering email to address {0}..
        /// </summary>
        public static string SmtpEmailSender_SmtpFail {
            get {
                return ResourceManager.GetString("SmtpEmailSender_SmtpFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown addressee type {0} in {1}..
        /// </summary>
        public static string SubscribersFetcher_UnknownAddresseeType {
            get {
                return ResourceManager.GetString("SubscribersFetcher_UnknownAddresseeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComposerId not set. Value can not be default..
        /// </summary>
        public static string Validation_ComposerIdNotSet {
            get {
                return ResourceManager.GetString("Validation_ComposerIdNotSet", resourceCulture);
            }
        }
    }
}
