//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignaloBot.Sender.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InternalMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InternalMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SignaloBot.Sender.Resources.InternalMessages", typeof(InternalMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Template matched delivery type {0}..
        /// </summary>
        public static string NoTemplateMatched {
            get {
                return ResourceManager.GetString("NoTemplateMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while delivering email to address {0}..
        /// </summary>
        public static string SmtpEmailSender_Fail {
            get {
                return ResourceManager.GetString("SmtpEmailSender_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smtp exception while delivering email to address {0}..
        /// </summary>
        public static string SmtpEmailSender_SmtpFail {
            get {
                return ResourceManager.GetString("SmtpEmailSender_SmtpFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal type {0} can not be sended. Expected type {1}..
        /// </summary>
        public static string SmtpEmailSender_WrongType {
            get {
                return ResourceManager.GetString("SmtpEmailSender_WrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComposerID not set. Value can not be default..
        /// </summary>
        public static string Validation_ComposerIDNotSet {
            get {
                return ResourceManager.GetString("Validation_ComposerIDNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} registered with {1} {2} value..
        /// </summary>
        public static string Validation_NoDispatchQueueAccepting {
            get {
                return ResourceManager.GetString("Validation_NoDispatchQueueAccepting", resourceCulture);
            }
        }
    }
}
