//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanatana.Notifications.DAL.EntityFrameworkCore.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InstallScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InstallScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sanatana.Notifications.DAL.EntityFrameworkCore.Resources.InstallScripts", typeof(InstallScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TYPE [pref].[ComposerSettingsType] AS TABLE(
        ///	[ComposerSettingsId] [bigint] NOT NULL,
        ///	[Name] varchar(max) NOT NULL,
        ///	[CategoryId] [int] NOT NULL,
        ///	[Subscription] varchar(max) NOT NULL,
        ///	[Updates] varchar(max) NOT NULL,
        ///	[CustomDispatchComposer] varchar(max) NOT NULL
        ///).
        /// </summary>
        internal static string type_ComposerSettings {
            get {
                return ResourceManager.GetString("type_ComposerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TYPE [pref].[DispatchTemplateType] AS TABLE(
        ///	[DispatchTemplateId] [bigint] NOT NULL,
        ///	[ComposerSettingsId] [bigint] NOT NULL,
        ///	[Name] varchar(max) NULL,
        ///	[DeliveryType] [int] NOT NULL,
        ///	[SchedulesSet] [int] NULL,
        ///	[IsActive] [bit] NOT NULL,
        ///	[DerivedEntityData] varchar(max) NOT NULL
        ///).
        /// </summary>
        internal static string type_DispatchTemplate {
            get {
                return ResourceManager.GetString("type_DispatchTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TYPE [pref].[SignalDispatchType] AS TABLE(
        ///	[SignalDispatchId] [bigint] NOT NULL,
        ///	[SendDateUtc] [datetime2](7) NOT NULL,
        ///	[IsScheduled] [bit] NOT NULL,
        ///	[FailedAttempts] [int] NOT NULL
        ///).
        /// </summary>
        internal static string type_SignalDispatch {
            get {
                return ResourceManager.GetString("type_SignalDispatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TYPE [pref].[SignalEventType] AS TABLE(
        ///	[SignalEventId] [bigint] NOT NULL,
        ///	[FailedAttempts] [int] NOT NULL,
        ///	[ComposerSettingsId] [int] NULL,
        ///	[SubscriberIdRangeFrom] [bigint] NULL,
        ///	[SubscriberIdRangeTo] [bigint] NULL,
        ///	[SubscriberIdFromDeliveryTypesHandled] [xml] NULL
        ///).
        /// </summary>
        internal static string type_SignalEvent {
            get {
                return ResourceManager.GetString("type_SignalEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TYPE [pref].[StoredNotificationType] AS TABLE(
        ///	[StoredNotificationId] [bigint] NOT NULL,
        ///	[SubscriberId] [bigint] NOT NULL,
        ///	[CategoryId] [int] NULL,
        ///	[TopicId] [nvarchar](max) NULL,
        ///	[CreateDateUtc] [datetime2](7) NOT NULL,
        ///	[MessageSubject] [nvarchar](max) NULL,
        ///	[MessageBody] [nvarchar](max) NULL
        ///).
        /// </summary>
        internal static string type_StoredNotification {
            get {
                return ResourceManager.GetString("type_StoredNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TYPE [pref].[SubscriberType] AS TABLE(
        ///	[SubscriberId] [bigint] NOT NULL,
        ///	[SendCount] [int] NOT NULL,
        ///	[DeliveryType] [int] NOT NULL,
        ///	[CategoryId] [int] NOT NULL,
        ///	[TopicId] [int] NULL
        ///).
        /// </summary>
        internal static string type_Subscriber {
            get {
                return ResourceManager.GetString("type_Subscriber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TYPE [pref].[SubscriberCategorySettingsType] AS TABLE(
        ///	[SubscriberId] [bigint] NOT NULL,
        ///	[GroupId] [bigint] NULL,
        ///	[DeliveryType] [int] NOT NULL,
        ///	[CategoryId] [int] NOT NULL,
        ///	[LastSendDateUtc] [datetime2](7) NULL,
        ///	[SendCount] [int] NOT NULL,
        ///	[IsEnabled] [bit] NOT NULL
        ///).
        /// </summary>
        internal static string type_SubscriberCategorySettings {
            get {
                return ResourceManager.GetString("type_SubscriberCategorySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TYPE [pref].[SubscriberCategorySettingsTypeIsEnabled] AS TABLE(
        ///	[SubscriberCategorySettingsId] [bigint] NOT NULL,
        ///	[IsEnabled] [bit] NOT NULL
        ///).
        /// </summary>
        internal static string type_SubscriberCategorySettingsIsEnabled {
            get {
                return ResourceManager.GetString("type_SubscriberCategorySettingsIsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TYPE [pref].[SubscriberNDRSettingsType] AS TABLE(
        ///	[SubscriberId] [bigint] NOT NULL,
        ///	[DeliveryType]  [int] NOT NULL,
        ///	[NDRCount] [int] NOT NULL,
        ///	[IsBlockedOfNDR] [bit] NOT NULL
        ///).
        /// </summary>
        internal static string type_SubscriberNDRSettings {
            get {
                return ResourceManager.GetString("type_SubscriberNDRSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TYPE [pref].[SubscriberTopicSettingsType] AS TABLE(
        ///	[TopicId] [nvarchar](1000) NOT NULL,
        ///	[CategoryId] [int] NOT NULL,
        ///	[DeliveryType] [int] NOT NULL,
        ///	[SubscriberId] [bigint] NOT NULL,
        ///	[AddDateUtc] [datetime2](7) NOT NULL,
        ///	[IsEnabled] [bit] NOT NULL
        ///).
        /// </summary>
        internal static string type_SubscriberTopicSettings {
            get {
                return ResourceManager.GetString("type_SubscriberTopicSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TYPE [pref].[SubscriberTopicSettingsTypeIsEnabled] AS TABLE(
        ///	[SubscriberTopicSettingsId] [bigint] NOT NULL,
        ///	[IsEnabled] [bit] NOT NULL
        ///).
        /// </summary>
        internal static string type_SubscriberTopicSettingsIsEnabled {
            get {
                return ResourceManager.GetString("type_SubscriberTopicSettingsIsEnabled", resourceCulture);
            }
        }
    }
}
