language: csharp
mono: none
dotnet: 2.1.2
solution: Sanatana.Notifications.sln
script:
  - dotnet pack Sanatana.Notifications/Sanatana.Notifications.csproj -o ../nuget -c Release
  - dotnet pack Sanatana.Notifications.DAL.EntityFrameworkCore/Sanatana.Notifications.DAL.EntityFrameworkCore.csproj -o ../nuget -c Release
  - dotnet pack Sanatana.Notifications.DAL.MongoDb/Sanatana.Notifications.DAL.MongoDb.csproj -o ../nuget -c Release
  - dotnet pack Sanatana.Notifications.NDR/Sanatana.Notifications.NDR.csproj -o ../nuget -c Release
  - dotnet pack Sanatana.Notifications.Dispatchers.AWS_SES/Sanatana.Notifications.Dispatchers.AWS_SES.csproj -o ../nuget -c Release
  - dotnet pack Sanatana.Notifications.NDR.AWS/Sanatana.Notifications.NDR.AWS.csproj -o ../nuget -c Release

  - dotnet nuget push nuget/Sanatana.Notifications.*.nupkg --force-english-output -k $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
  - dotnet nuget push nuget/Sanatana.Notifications.DAL.EntityFrameworkCore.*.nupkg --force-english-output -k $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
  - dotnet nuget push nuget/Sanatana.Notifications.DAL.MongoDb.*.nupkg --force-english-output -k $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
  - dotnet nuget push nuget/Sanatana.Notifications.NDR.*.nupkg --force-english-output -k $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
  - dotnet nuget push nuget/Sanatana.Notifications.Dispatchers.AWS_SES.*.nupkg --force-english-output -k $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
  - dotnet nuget push nuget/Sanatana.Notifications.NDR.AWS.*.nupkg --force-english-output -k $NUGET_API_KEY --source https://api.nuget.org/v3/index.json