//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignaloBot.Demo.Client.App_Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewContent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewContent() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SignaloBot.Demo.Client.App_Resources.ViewContent", typeof(ViewContent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to simple SignaloBot demo where you can try out some features as Message templating, Querying for subscribers and Enqueing messages for delivery..
        /// </summary>
        public static string Home_Index_Description {
            get {
                return ResourceManager.GetString("Home_Index_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform a query to database to select subscribers from all users and enqueue a message for them..
        /// </summary>
        public static string Home_Index_SendMessage {
            get {
                return ResourceManager.GetString("Home_Index_SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a delivery.
        /// </summary>
        public static string Home_Index_SendTitle {
            get {
                return ResourceManager.GetString("Home_Index_SendTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Home_Index_Start {
            get {
                return ResourceManager.GetString("Home_Index_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Page.
        /// </summary>
        public static string Home_Index_Title {
            get {
                return ResourceManager.GetString("Home_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observe and add new users that will receive notifications..
        /// </summary>
        public static string Home_Index_UsersMessage {
            get {
                return ResourceManager.GetString("Home_Index_UsersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage subscribers.
        /// </summary>
        public static string Home_Index_UsersTitle {
            get {
                return ResourceManager.GetString("Home_Index_UsersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit.
        /// </summary>
        public static string Home_Index_Visit {
            get {
                return ResourceManager.GetString("Home_Index_Visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add message.
        /// </summary>
        public static string Home_Send_AddTitle {
            get {
                return ResourceManager.GetString("Home_Send_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed send attempts.
        /// </summary>
        public static string Home_Send_FailedAttemptsCol {
            get {
                return ResourceManager.GetString("Home_Send_FailedAttemptsCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is delayed.
        /// </summary>
        public static string Home_Send_IsDelayedCol {
            get {
                return ResourceManager.GetString("Home_Send_IsDelayedCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send queue.
        /// </summary>
        public static string Home_Send_QueueTitle {
            get {
                return ResourceManager.GetString("Home_Send_QueueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver.
        /// </summary>
        public static string Home_Send_ReceiverCol {
            get {
                return ResourceManager.GetString("Home_Send_ReceiverCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message enqueued for {0} subscribers.
        /// </summary>
        public static string Home_Send_ResultSuccessful {
            get {
                return ResourceManager.GetString("Home_Send_ResultSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Home_Send_Send {
            get {
                return ResourceManager.GetString("Home_Send_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        public static string Home_Send_SenderCol {
            get {
                return ResourceManager.GetString("Home_Send_SenderCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send demo message to a database queue..
        /// </summary>
        public static string Home_Send_SendMessage {
            get {
                return ResourceManager.GetString("Home_Send_SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send time.
        /// </summary>
        public static string Home_Send_SendTimeCol {
            get {
                return ResourceManager.GetString("Home_Send_SendTimeCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Home_Send_SubjectCol {
            get {
                return ResourceManager.GetString("Home_Send_SubjectCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        public static string Home_Send_Title {
            get {
                return ResourceManager.GetString("Home_Send_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignaloBot.
        /// </summary>
        public static string Layout_ApplicationName {
            get {
                return ResourceManager.GetString("Layout_ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Layout_Menu_Home {
            get {
                return ResourceManager.GetString("Layout_Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        public static string Layout_Menu_Send {
            get {
                return ResourceManager.GetString("Layout_Menu_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Layout_Menu_Users {
            get {
                return ResourceManager.GetString("Layout_Menu_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid email required.
        /// </summary>
        public static string NewUserVM_InvalidEmailError {
            get {
                return ResourceManager.GetString("NewUserVM_InvalidEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive emails.
        /// </summary>
        public static string NewUserVM_IsEmailEnabled {
            get {
                return ResourceManager.GetString("NewUserVM_IsEmailEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User added.
        /// </summary>
        public static string Users_Add_AddSuccessful {
            get {
                return ResourceManager.GetString("Users_Add_AddSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new user.
        /// </summary>
        public static string Users_Add_AddTitle {
            get {
                return ResourceManager.GetString("Users_Add_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string Users_Add_BackToList {
            get {
                return ResourceManager.GetString("Users_Add_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email {0} already exists.
        /// </summary>
        public static string Users_Add_EmailExists {
            get {
                return ResourceManager.GetString("Users_Add_EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Users_Add_Save {
            get {
                return ResourceManager.GetString("Users_Add_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user.
        /// </summary>
        public static string Users_Add_Title {
            get {
                return ResourceManager.GetString("Users_Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new user.
        /// </summary>
        public static string Users_List_AddUser {
            get {
                return ResourceManager.GetString("Users_List_AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Users_List_EmailAddressCol {
            get {
                return ResourceManager.GetString("Users_List_EmailAddressCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email enabled.
        /// </summary>
        public static string Users_List_EmailEnabledCol {
            get {
                return ResourceManager.GetString("Users_List_EmailEnabledCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users list.
        /// </summary>
        public static string Users_List_ListTitle {
            get {
                return ResourceManager.GetString("Users_List_ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users list.
        /// </summary>
        public static string Users_List_Title {
            get {
                return ResourceManager.GetString("Users_List_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserID.
        /// </summary>
        public static string Users_List_UserIDCol {
            get {
                return ResourceManager.GetString("Users_List_UserIDCol", resourceCulture);
            }
        }
    }
}
