//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignaloBot.Demo.Client.SignaloBot.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SignaloBot.Service.ISignalServiceOf_ObjectId")]
    public interface ISignalServiceOf_ObjectId {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignalServiceOf_ObjectId/RaiseKeyValueEvent", ReplyAction="http://tempuri.org/ISignalServiceOf_ObjectId/RaiseKeyValueEventResponse")]
        void RaiseKeyValueEvent(System.Nullable<MongoDB.Bson.ObjectId> groupID, System.Nullable<MongoDB.Bson.ObjectId> userID, int categoryID, string topicID, System.Collections.Generic.Dictionary<string, string> values);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignalServiceOf_ObjectId/RaiseKeyValueEvent", ReplyAction="http://tempuri.org/ISignalServiceOf_ObjectId/RaiseKeyValueEventResponse")]
        System.Threading.Tasks.Task RaiseKeyValueEventAsync(System.Nullable<MongoDB.Bson.ObjectId> groupID, System.Nullable<MongoDB.Bson.ObjectId> userID, int categoryID, string topicID, System.Collections.Generic.Dictionary<string, string> values);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISignalServiceOf_ObjectIdChannel : ISignalServiceOf_ObjectId, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SignalServiceOf_ObjectIdClient : System.ServiceModel.ClientBase<Service.ISignalServiceOf_ObjectId>, ISignalServiceOf_ObjectId {
        
        public SignalServiceOf_ObjectIdClient() {
        }
        
        public SignalServiceOf_ObjectIdClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SignalServiceOf_ObjectIdClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignalServiceOf_ObjectIdClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignalServiceOf_ObjectIdClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RaiseKeyValueEvent(System.Nullable<MongoDB.Bson.ObjectId> groupID, System.Nullable<MongoDB.Bson.ObjectId> userID, int categoryID, string topicID, System.Collections.Generic.Dictionary<string, string> values) {
            base.Channel.RaiseKeyValueEvent(groupID, userID, categoryID, topicID, values);
        }
        
        public System.Threading.Tasks.Task RaiseKeyValueEventAsync(System.Nullable<MongoDB.Bson.ObjectId> groupID, System.Nullable<MongoDB.Bson.ObjectId> userID, int categoryID, string topicID, System.Collections.Generic.Dictionary<string, string> values) {
            return base.Channel.RaiseKeyValueEventAsync(groupID, userID, categoryID, topicID, values);
        }
    }
}
