//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignaloBot.Initializer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InnerMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InnerMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SignaloBot.Initializer.Resources.InnerMessages", typeof(InnerMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignaloBot: Create core SQL scripts.
        /// </summary>
        internal static string CoreScripts_Intro {
            get {
                return ResourceManager.GetString("CoreScripts_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignaloBot: Drop MongoDb database.
        /// </summary>
        internal static string DropMongoDb_Intro {
            get {
                return ResourceManager.GetString("DropMongoDb_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignaloBot: Drop SQL database.
        /// </summary>
        internal static string DropSqlDb_Intro {
            get {
                return ResourceManager.GetString("DropSqlDb_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignaloBot: Create load test data.
        /// </summary>
        internal static string LoadTestData_Intro {
            get {
                return ResourceManager.GetString("LoadTestData_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% complete.
        /// </summary>
        internal static string LoadTestData_PercentMessage {
            get {
                return ResourceManager.GetString("LoadTestData_PercentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignaloBot: Create MongoDb indexes.
        /// </summary>
        internal static string MongoDbIndex_Intro {
            get {
                return ResourceManager.GetString("MongoDbIndex_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignaloBot: Create notification SQL scripts.
        /// </summary>
        internal static string NotificationScripts_Intro {
            get {
                return ResourceManager.GetString("NotificationScripts_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignaloBot: Create test data.
        /// </summary>
        internal static string TestData_Intro {
            get {
                return ResourceManager.GetString("TestData_Intro", resourceCulture);
            }
        }
    }
}
